eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
server:
  port: 9991
spring:
  application:
    name: admin-bff
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
            - SaveSession
            - TokenRelay=
          routes:
            - id: adminbff
              uri: http://localhost:3001
              predicates:
                - Path=/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-adminbff:
            issuer-uri: http://localhost:9090
        registration:
          itp-adminbff:
            provider:  itp-adminbff
            client-id:  itp-adminbff
            client-secret: qwerqwer
            redirect-uri: http://localhost:9991/login/oauth2/code/itp-adminbff
            authorization-grant-type:
              - authorization_code
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email
