eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
server:
  port: 20262
spring:
  application:
    name: pipeline-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    function:
      definition: processProduct;processMessage;processProductDetail;processDebeziumProduct;processOracleXmlData
    stream:
      bindings:
        processProductDetail-in-0:
          destination: product-detail # topic_name
          group: monitor-group2 # consumer_group_id
          content-type: application/json
        processProduct-in-0:
          destination: test-product # topic_name
          group: monitor-group # consumer_group_id
          content-type: application/json
        processMessage-in-0:
          destination: test-topic
        processProductDetail-out-0:
          destination: processed-product-detail
          content-type: application/json
        processDebeziumProduct-in-0:
          destination: dbz_server.public.products
          group: debezium-consumer
        processOracleXmlData-in-0:
          destination: ITP.CORE_BANKING.RECORD_XML
          group: oracle-xml-data-consumer
#          content-type: application/json
      kafka:
        binder:
          brokers: localhost:29092,localhost:29094,localhost:29096
          configuration:
            auto.offset.reset: earliest

        bindings:
          processDebeziumProduct-in-0:
            consumer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                spring.deserializer.key.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
                spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
                specific.avro.reader: false
          processOracleXmlData-in-0:
            consumer:
              configuration:
                schema.registry.url: http://localhost:8081
                key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                spring.deserializer.key.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
                spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
                specific.avro.reader: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type: client_credentials
#              - authorization_code
#              - refresh_token
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email
# Resilience4J
resilience4j:
  circuitbreaker:
    instances:
      account:
        sliding-window-size: 10
        failure-rate-threshold: 50 # Percentages
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Log Debug
logging:
  level:
    co.istad.polin.pipeline_service: DEBUG